### ISSUE TITLE
Error while cache warming

### ISSUE THREAD

**Issue by abdulvajid4525** [eapowertools/CacheInitializer#18]
Hi Team,

While I run the below command in command prompt, an error is coming "Ticket retreival failed."
CacheInitializer.exe --server https://xyz.abc.qwe.net --appid fddfhgffg43654fcghfj

When I added the virtual proxy prefix, another error is coming "Sequence contains no matching element"
CacheInitializer.exe --server https://xyz.abc.qwe.net --appid fddfhgffg43654fcghfj --proxy win

Could you please help on this.

Thank you

**Comment by abdulvajid4525** [comment]
Hi,

Can you please provide any updates.

Thanks and regards
Vajid

**Comment by jparis** [comment]
what does your virtual proxy configuration look like? do you have one named win?

**Comment by abdulvajid4525** [comment]
Yes

**Comment by jparis** [comment]
ah, the user you are running as can't find an App with that ID.

**Comment by abdulvajid4525** [comment]
Yes, it's working with service account. Thank you
