### ISSUE TITLE
Error while generating exe

### ISSUE THREAD

**Issue by tooltime22** [eapowertools/CacheInitializer#5]
Hi, thanks for your development.

During debugging/building an exe File a get an error:

i did the following steps:
- I downloaded the zip file from here and extracted it
- installed Visual Studio 2015
- opened Project (sln File)
- then click on the Start Button
- Visual Studio reported an Error in Line 72 "     remoteQlikSenseLocation.AsNtlmUserViaProxy(isHTTPs,null,false);
Failure "CS1501	Keine Überladung für die AsNtlmUserViaProxy-Methode nimmt 3 Argumente an."

When i clicked on the failure i got the bing search Field filled with this:
CS1501  C# No overload for method takes 3 arguments 

Unfortunately i'm a total newbie to Visual Studio, so i can't really help myself. 
Is this a bug?

Would it be possible you give me some hints or maybe get a working exe from you?

thanks for your time

**Comment by jparis** [comment]
Realize this is super old. but will be posting an exe soon.
