### ISSUE TITLE
Doesn't able to cache when have many sheets and objects.

### ISSUE THREAD

**Issue by JoneyQuest** [eapowertools/CacheInitializer#7]
Hi, Thank you for outstanding work. This is working when i have 2-5 sheets. I have an application where there are 50 sheets and there are 200 objects total all (also shows in command prompt when use this). 
Cache initializer  try to cache for 30-40 minutes but not able to complete it. 
I have tried used one selection with -f -v -o command. It applies selections but not able to cache objects which is key objective of this. 
Is there any limitation on this where it is unable to cache after spending significant time for each?

**Comment by mohit-llp** [comment]
Hi,
I got an error.
The remote server returned an error: (401) Unauthorized.

If i used certificates then i got an error
The remote certificate is invalid according to the validation procedure.

please help

**Comment by jparis** [comment]
Closing this as it's an old issue. Added additional logging, you can grab the latest .exe from the releases. Try again and open if it's still a problem.
